demo_run: false
demo_conf:
  algos_to_test:
  - dijkstra
  - bellmanford
  - bmssp
  save_result_path: results
custom_dataset_run: false
custom_dataset_conf:
  graph_path: benchmark/datasets/road-minnesota.mtx
  directed_graph: false
  algos_to_test:
  - dijkstra
  - bellmanford
  - bmssp
  save_result_path: results
scaling_benchmark_run: true
scaling_benchmark_conf:
  min_nodes:  10
  max_nodes:  1e7
  max_in_degree: 2
  max_out_degree: 2
  num_steps: 7
  edge_ratios: 
  - 1.2
  - 1.5
  - 1.8
  algos_to_test:
  - dijkstra
  - bellmanford
  - bmssp
  exclude_algos_above:
  - ["bmssp", 1e3]
  - ["bellmanford", 1e4]
  seed: 42
  num_trials: 3
  save_result_path: results
